### ISSUE TITLE
Can't get webkit2png to work on Manjaro

### ISSUE THREAD

**Issue by unfa** [adamn/python-webkit2png#73]
Hi!

I know this project is not maintained, but maybe someone would be able to help me.

I've installed webkit2png from AUR, but whe nI run it I get this:

    $ webkit2png --help
    Traceback (most recent call last):
      File "/usr/bin/webkit2png", line 11, in <module>
        load_entry_point('webkit2png==0.8.3', 'console_scripts', 'webkit2png')()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
        return ep.load()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
        return self.resolve()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/lib/python2.7/site-packages/webkit2png/__init__.py", line 1, in <module>
        from webkit2png import WebkitRenderer
      File "/usr/lib/python2.7/site-packages/webkit2png/webkit2png.py", line 31, in <module>
        from PyQt4.QtWebKit import *
    ImportError: No module named QtWebKit

I have qtwebkit installed, and even pyqt4 bindings for Python 2 and Python 3.
Still no go.

Is there any alternative I could use to produce high-resolution PNG images of websites?

**Comment by supersonictw** [comment]
https://github.com/adamn/python-webkit2png/issues/67#issuecomment-609031258
